name: dispatch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  change_app_package_name: ^1.1.0
  chat_bubbles: ^1.4.1
  cloud_functions: ^4.4.0
  convex_bottom_bar: ^3.2.0
  custom_refresh_indicator: ^2.2.1
  dotted_line: ^3.2.2
  dropdown_search: ^5.0.6
  firebase_auth: ^4.9.0
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.1
  flutter_login: ^4.2.1
  flutter_profile_picture: ^2.0.0
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.0.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  phone_form_field: ^8.1.0
  queue: ^3.1.0+2
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Dispatch.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
