name: dispatch
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  chat_bubbles: ^1.4.1
  convex_bottom_bar: ^3.2.0
  custom_refresh_indicator: ^2.2.1
  dotted_line: ^3.2.2
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.0.0
  flutter_profile_picture: ^2.0.0
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^9.0.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
  phone_form_field: ^8.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
