// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFl_xVUDUj3xsU19WXdf-2IiIfPN5JeRM',
    appId: '1:509788095788:web:9411a9e6a8a51019429889',
    messagingSenderId: '509788095788',
    projectId: 'dispatch-muneshwers',
    authDomain: 'dispatch-muneshwers.firebaseapp.com',
    databaseURL: 'https://dispatch-muneshwers-default-rtdb.firebaseio.com',
    storageBucket: 'dispatch-muneshwers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7CD8m837mXkIFgL3TaPXrhfBCHSfNY4c',
    appId: '1:509788095788:android:dcf749e07536e29d429889',
    messagingSenderId: '509788095788',
    projectId: 'dispatch-muneshwers',
    databaseURL: 'https://dispatch-muneshwers-default-rtdb.firebaseio.com',
    storageBucket: 'dispatch-muneshwers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqdnrxz3rHldHLV9zYLfiMrKjQB3whT8',
    appId: '1:509788095788:ios:0939dd7636301586429889',
    messagingSenderId: '509788095788',
    projectId: 'dispatch-muneshwers',
    databaseURL: 'https://dispatch-muneshwers-default-rtdb.firebaseio.com',
    storageBucket: 'dispatch-muneshwers.appspot.com',
    iosClientId: '509788095788-l0f4vkimqn7d8ljhodf5jecfd3j4aqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dispatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqdnrxz3rHldHLV9zYLfiMrKjQB3whT8',
    appId: '1:509788095788:ios:8bd84e903b235b14429889',
    messagingSenderId: '509788095788',
    projectId: 'dispatch-muneshwers',
    databaseURL: 'https://dispatch-muneshwers-default-rtdb.firebaseio.com',
    storageBucket: 'dispatch-muneshwers.appspot.com',
    iosClientId: '509788095788-ndi3i78ka6c904k2oj3809hd1tod12e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dispatch.RunnerTests',
  );
}
